### PR TITLE
Removing add-on NGC 6826

### PR DESCRIPTION
**Pull request by SpaceExplorer2008**
Some of the sprites no longer work correctly (they have become invisible).

### CODE REVIEW

**Comment by DaveBowman2001** [comment]
Probably best if we raise a new issue regarding sprite models bugging....this also occurs on the V838 Mon addon as well

**Comment by SpaceExplorer2008** [comment]
I already mentioned this once with pelagornithid, it seems that they are sprites whose codes are having problems, and that Celestia can no longer read them (could only in the past). 
I don't know how to fix them.

**Comment by DaveBowman2001** [comment]
I'll try using CMODView to see if it can be fixed there

**Comment by DaveBowman2001** [comment]
Looks like CMODView did the trick...it was now fixed (updated at #1981)
Screenshot_2024-09-12-21-44-25-133_space celestia mobilecelestia

**Pull request closed without merging**
