### PR TITLE
My Little pony planet

### PR DESCRIPTION
**Pull request by IgorXXXmirror**
...

### CODE REVIEW

**Comment by Karistus** [comment]
The way you've structured your files makes this add-on impossible to open in Celestia. All your files need to be in the main folder, there can't be any sub folders (i.e the"effects" folder and the other folder in Russian need to be removed, and their content merged into the main MLP folder)

**Comment by Karistus** [comment]
You also dont need to list BumpMap and NormalMap, you can only use one

**Comment by IgorXXXmirror** [comment]
I made it based on other add-ons, they are structured exactly like this on
my Android.

сб, 6 апр. 2024 г., 06:17 DaveBowman2001 ***@***.***>:

**Comment by IgorXXXmirror** [comment]
My version catalogue work.

вс, 7 апр. 2024 г., 19:03 IgorXXXmirror Prower ***@***.***>:

**Pull request closed without merging**
